# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Tasks\Work\VoltageSetting\VoltageSetting.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(450, 200)
        Dialog.setMinimumSize(QtCore.QSize(450, 200))
        Dialog.setMaximumSize(QtCore.QSize(450, 200))
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(False)
        self.pushButton_Set = QtWidgets.QPushButton(Dialog)
        self.pushButton_Set.setGeometry(QtCore.QRect(120, 130, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Set.setFont(font)
        self.pushButton_Set.setObjectName("pushButton_Set")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(297, 20, 141, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_Plus1 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Plus1.setFont(font)
        self.pushButton_Plus1.setObjectName("pushButton_Plus1")
        self.gridLayout.addWidget(self.pushButton_Plus1, 0, 0, 1, 1)
        self.pushButton_Sub1 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Sub1.setFont(font)
        self.pushButton_Sub1.setObjectName("pushButton_Sub1")
        self.gridLayout.addWidget(self.pushButton_Sub1, 0, 1, 1, 1)
        self.pushButton_Plus10 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Plus10.setFont(font)
        self.pushButton_Plus10.setObjectName("pushButton_Plus10")
        self.gridLayout.addWidget(self.pushButton_Plus10, 1, 0, 1, 1)
        self.pushButton_Sub10 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Sub10.setFont(font)
        self.pushButton_Sub10.setObjectName("pushButton_Sub10")
        self.gridLayout.addWidget(self.pushButton_Sub10, 1, 1, 1, 1)
        self.pushButton_Plus100 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Plus100.setFont(font)
        self.pushButton_Plus100.setObjectName("pushButton_Plus100")
        self.gridLayout.addWidget(self.pushButton_Plus100, 2, 0, 1, 1)
        self.pushButton_Sub100 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Sub100.setFont(font)
        self.pushButton_Sub100.setObjectName("pushButton_Sub100")
        self.gridLayout.addWidget(self.pushButton_Sub100, 2, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 50, 281, 40))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_Vol = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_Vol.setFont(font)
        self.label_Vol.setObjectName("label_Vol")
        self.horizontalLayout.addWidget(self.label_Vol)
        self.lineEdit_Vol = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_Vol.setBaseSize(QtCore.QSize(410, 180))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.lineEdit_Vol.setFont(font)
        self.lineEdit_Vol.setObjectName("lineEdit_Vol")
        self.horizontalLayout.addWidget(self.lineEdit_Vol)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Voltage Setting"))
        self.pushButton_Set.setText(_translate("Dialog", "Set Voltage"))
        self.pushButton_Plus1.setText(_translate("Dialog", "+"))
        self.pushButton_Sub1.setText(_translate("Dialog", "-"))
        self.pushButton_Plus10.setText(_translate("Dialog", "++"))
        self.pushButton_Sub10.setText(_translate("Dialog", "--"))
        self.pushButton_Plus100.setText(_translate("Dialog", "+++"))
        self.pushButton_Sub100.setText(_translate("Dialog", "---"))
        self.label_Vol.setText(_translate("Dialog", "Voltage:"))
        self.lineEdit_Vol.setText(_translate("Dialog", "1.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

